export const EMPTY_STATE = {
  price: 0,
  stock: 0,
  category: 0,
  name: '',
  image: [],
  imageString: '',
  comments: [],
  description: '',
  discount: 0,
  rating: {
    oneStar: 0,
    twoStar: 0,
    threeStar: 0,
    fourStar: 0,
    fiveStar: 0,
    usersRating: 0,
    total: 0,
  },
};
